services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - /mongo-data:/data/db
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: my-database
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - /redis-data:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass root123
    ports:
      - '6379:6379'

volumes:
  mongo_data:
  redis_data:
